### ISSUE TITLE
Script Causes redgifs videos to be off-centre/cut off

### ISSUE THREAD

**Issue by 8ars1** [Invertex/RedGifs-AutoHD#14]
Hi, the redgifs autoHD script seems to cause the gifs to be off-centre to the right which sometimes leads to the gif being cut off on the right side. This had been true for some time but only recently did the left-right scroll bar disappear so it's now impossible to see the right side of some gifs while on redgifs.

**Comment by Invertex** [comment]
I was putting off updating it until Gfycat fully closed down. I've pushed an update, which should convert the script to RedGifs only. 

Run Update Scripts Twice and it should change name in your script manager to RedGifs AutoHD (may also need to refresh the page you're on.)

**Comment by 8ars1** [comment]
That seems to have worked. Thanks!
