### ISSUE TITLE
Doesn't change download video link to HD version

### ISSUE THREAD

**Issue by iwejfnd** [Invertex/RedGifs-AutoHD#17]
Hey, not sure if this is meant to be covered by this plugin - 
When trying to download a gif via right click -> save as (on firefox if that helps diagnose it), it downloads the -mobile version. I'm not sure if this is because the script doesn't work, or if it just doesn't change the download link to the HD version.
Either way, it would be nice to be able to default to downloading the HD version of gifs rather than the mobile/low res version.
Thanks :)

**Comment by Invertex** [comment]
Hi, make sure your version is actually updated. The transition from the older filename to the new didn't quite work I think.

Try clicking this link https://github.com/Invertex/RedGifs-AutoHD/raw/master/RedGifs%20AutoHD.user.js

**Comment by Invertex** [comment]
@iwejfnd

**Comment by iwejfnd** [comment]
I tried updating with that link, but it doesn't seem to have helped. According to Greasemonkey, it's active and running.
Also, I can't see a download button in either RES embeds or on redgifs.com itself, so it's possible that the script isn't working properly on my end. Not sure why this would be, since it seems to be "active". Any suggestions?

**Comment by Invertex** [comment]
> I tried updating with that link, but it doesn't seem to have helped. According to Greasemonkey, it's active and running. Also, I can't see a download button in either RES embeds or on redgifs.com itself, so it's possible that the script isn't working properly on my end. Not sure why this would be, since it seems to be "active". Any suggestions?

You can maybe see if the old one is still installed, Gfycat-AutoHD, or if there's two different copies of RedGifs-AutoHD.
Safest bet would be to just remove both and the install from that link.

What browser are you using btw?  Also if your browser supports Tampermonkey, us it instead, it is more feature-rich.

**Comment by iwejfnd** [comment]
Hey, looks like Greasemonkey was the issue for me! I installed Tampermonkey and the script is working perfectly now.
I didn't have another old version of the script running, and I'm using Firefox. Thanks for the help and the script :)
