### ISSUE TITLE
Can't download videos from a specific user

### ISSUE THREAD

**Issue by KrissKim-rgb** [Invertex/RedGifs-AutoHD#18]
I have no idea, but I can't download videos from a specific users. see: [link](https://www.redgifs.com/users/thereturnofsage)

I can download other videos without any issue.

I tried to add some `GM_download` but I couldn't get any callback from there.

I wonder whether it's specific to my environment (e.g. slow network).
Can someone check this?

My environment:
 - Tampermonkey: 5.2.0
 - Your script: latest
 -  Windows 10 + latest Chrome

**Comment by Invertex** [comment]
Works fine for me, whether I go to an individual video or view their profile as a feed.
Is  there a specific video you tried that doesn't work? I tried multiple and didn't have an issue.

Win 10, latest Chrome, but my Tampermonkey is 5.2.3, so you could try updating your addon if it's actually 5.2.0.

**Comment by KrissKim-rgb** [comment]
I don't know why, but I can't reproduce this now..
